AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  uploadimage:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: upload_image
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./upload_image
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::642155208155:role/S3_full_access'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /upload_image
            Method: ANY
        Api2:
          Type: Api
          Properties:
            Path: /upload
            Method: POST
  lf1a2:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: lf1_a2
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./lf1_a2
      Description: ''
      MemorySize: 128
      Timeout: 60
      Role: 'arn:aws:iam::642155208155:role/service-role/lf1_a2-role-txv3zc01'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: Bucket1
            Events:
              - 's3:ObjectCreated:Put'
  lf2a2:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: lf2_a2
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: ./lf2_a2
      Description: ''
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::642155208155:role/service-role/lf1_a2-role-txv3zc01'
      Events:
        Api1:
          Type: Api
          Properties:
            Path: /search
            Method: GET

  Bucket1:
    Type: 'AWS::S3::Bucket'
